//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vtdi_Gatelog
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GateInDatabaseEntities : DbContext
    {
        public GateInDatabaseEntities()
            : base("name=GateInDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<ItemstoDeclare> ItemstoDeclares { get; set; }
        public virtual DbSet<Purpose> Purposes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vehicletype> Vehicletypes { get; set; }
        public virtual DbSet<GateInTable> GateInTables { get; set; }
    }
}
